# Generated by Django 5.0.14 on 2026-02-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toursession',
            name='booking_channel',
            field=models.CharField(blank=True, choices=[('online', 'Online Platform'), ('walkin', 'Walk-in'), ('direct', 'Direct Sales')], help_text='How the tour was booked', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='toursession',
            name='visitor_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of visitors for this tour', null=True),
        ),
        migrations.AddField(
            model_name='toursession',
            name='visitor_type',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('international', 'International')], help_text='Type of visitors (Local or International)', max_length=20, null=True),
        ),
    ]
