# Generated by Django 5.0.14 on 2026-02-15 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_toursession_booking_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRestaurantSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this restaurant schedule', unique=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether this schedule has been published to staff')),
                ('published_at', models.DateTimeField(blank=True, help_text='When this schedule was published', null=True)),
                ('notes', models.TextField(blank=True, help_text="Optional notes for this day's schedule")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Restaurant Schedule',
                'verbose_name_plural': 'Daily Restaurant Schedules',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('kitchen', 'Kitchen Staff'), ('serving', 'Serving Staff')], help_text='Type of staff: Kitchen or Serving', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this staff member is currently active')),
                ('hire_date', models.DateField(blank=True, help_text='Date when staff was hired', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant Staff',
                'verbose_name_plural': 'Restaurant Staff',
                'ordering': ['staff_type', 'user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Shift start time (e.g., 10:00 AM)')),
                ('end_time', models.TimeField(help_text='Shift end time (e.g., 6:00 PM)')),
                ('duration_hours', models.IntegerField(choices=[(4, '4 hours (Half-day)'), (8, '8 hours (Full-day)')], default=8, help_text='Shift duration: 4 hours (half-day) or 8 hours (full-day)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='scheduling.dailyrestaurantschedule')),
                ('staff', models.ForeignKey(blank=True, help_text='Assigned staff member (or None if unassigned)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='scheduling.restaurantstaff')),
            ],
            options={
                'verbose_name': 'Staff Shift',
                'verbose_name_plural': 'Staff Shifts',
                'ordering': ['daily_schedule__date', 'start_time', 'staff__staff_type'],
            },
        ),
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True, help_text='Whether staff is available on this date')),
                ('notes', models.TextField(blank=True, help_text='Optional notes (e.g., reason for unavailability)')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='scheduling.restaurantstaff')),
            ],
            options={
                'verbose_name': 'Staff Availability',
                'verbose_name_plural': 'Staff Availability',
                'ordering': ['date', 'staff'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
