# Generated by Django 5.0.14 on 2026-02-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0003_dailyrestaurantschedule_restaurantstaff_staffshift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantStaff',
            fields=[
            ],
            options={
                'verbose_name': 'Kitchen and serving staff',
                'verbose_name_plural': 'Kitchen and serving staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.restaurantstaff',),
        ),
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
            ],
            options={
                'verbose_name': 'Kitchen and serving staff availability',
                'verbose_name_plural': 'Kitchen and serving staff availabilities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scheduling.staffavailability',),
        ),
    ]
